In [1]:
import pandas as pd
from pandas import DataFrame

df1 = DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1':range(7)})
df2 = DataFrame({'key':['a', 'b', 'd'],
                'data2': range(3)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [2]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [3]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [4]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [5]:
df3 = DataFrame({'lkey': ['b','b','a','c','a','a','b'],
                'data1':range(7)})
df4 = DataFrame({'rkey':['a', 'b', 'd'],
                'data2': range(3)})
pd.merge(df3,df4,left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [6]:
pd.merge(df1, df2, how='outer')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c    NaN
7    NaN   d      2

In [7]:
df1 = DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'b'],
                'data1': range(6)})
df2 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                'data2': range(5)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [8]:
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [9]:
pd.merge(df1,df2, on='key', how='left')

data1 key  data2
0       0   b      1
1       0   b      3
2       1   b      1
3       1   b      3
4       2   a      0
5       2   a      2
6       3   c    NaN
7       4   a      0
8       4   a      2
9       5   b      1
10      5   b      3

In [10]:
pd.merge(df1,df2, how='inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [15]:
left = DataFrame({'key1': ['foo', 'foo', 'bar'],
                 'key2' : ['one', 'two', 'one'],
                 'lval': [1,2,3]})
right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                  'key2' : ['one', 'one', 'one', 'two'],
                  'rval' : [4, 5, 6, 7]})

In [16]:
pd.merge(left,right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  foo  two     2   NaN
3  bar  one     3     6
4  bar  two   NaN     7

In [19]:
pd.merge(left,right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [21]:
left1 = DataFrame({'key':['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [22]:
right1

group_val
a        3.5
b        7.0

In [23]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [26]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [28]:
import numpy as np
lefth = DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio','Nevada', 'Nevada'],
                   'key2' : [2000, 2001, 2002, 2001, 2002],
                   'data' : np.arange(5.)})
righth = DataFrame(np.arange(12).reshape((6, 2)),
                  index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                        [2001, 2000, 2000, 2000, 2001, 2002]],
                  columns=['event1', 'event2'])
lefth

data    key1  key2
0     0    Ohio  2000
1     1    Ohio  2001
2     2    Ohio  2002
3     3  Nevada  2001
4     4  Nevada  2002

In [29]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [30]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

data    key1  key2  event1  event2
0     0    Ohio  2000       4       5
0     0    Ohio  2000       6       7
1     1    Ohio  2001       8       9
2     2    Ohio  2002      10      11
3     3  Nevada  2001       0       1

In [31]:
pd.merge(lefth, righth, left_on=['key1', 'key2'],
        right_index=True, how='outer')

data    key1  key2  event1  event2
0     0    Ohio  2000       4       5
0     0    Ohio  2000       6       7
1     1    Ohio  2001       8       9
2     2    Ohio  2002      10      11
3     3  Nevada  2001       0       1
4     4  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000       2       3

In [33]:
left2 = DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                 index=['a', 'c', 'e'],
                 columns=['Ohio', 'Nevada'])
right2 = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13.,14.]],
                  index=['b', 'c', 'd', 'e'],
                  columns=['Missouri', 'Alabama'])
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [34]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [35]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a     1       2       NaN      NaN
b   NaN     NaN         7        8
c     3       4         9       10
d   NaN     NaN        11       12
e     5       6        13       14

In [36]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a     1       2       NaN      NaN
b   NaN     NaN         7        8
c     3       4         9       10
d   NaN     NaN        11       12
e     5       6        13       14

In [37]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [38]:
another = DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                   index=['a', 'c', 'e', 'f'], columns=['New York', 'Oregon'])
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2       NaN      NaN         7       8
c     3       4         9       10         9      10
e     5       6        13       14        11      12

In [39]:
left2.join([right2, another], how='outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2       NaN      NaN         7       8
b   NaN     NaN         7        8       NaN     NaN
c     3       4         9       10         9      10
d   NaN     NaN        11       12       NaN     NaN
e     5       6        13       14        11      12
f   NaN     NaN       NaN      NaN        16      17

In [40]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [44]:
from pandas import Series
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [45]:
pd.concat([s1, s2, s3], axis=1)

0   1   2
a   0 NaN NaN
b   1 NaN NaN
c NaN   2 NaN
d NaN   3 NaN
e NaN   4 NaN
f NaN NaN   5
g NaN NaN   6

In [46]:
s4 = pd.concat([s1 * 5, s3])
pd.concat([s1, s4], axis=1)

0  1
a   0  0
b   1  5
f NaN  5
g NaN  6

In [47]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [48]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']])

0   1
a   0   0
c NaN NaN
b   1   5
e NaN NaN

In [49]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [50]:
result.unstack()

a   b   f   g
one     0   1 NaN NaN
two     0   1 NaN NaN
three NaN NaN   5   6

In [51]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

one  two  three
a    0  NaN    NaN
b    1  NaN    NaN
c  NaN    2    NaN
d  NaN    3    NaN
e  NaN    4    NaN
f  NaN  NaN      5
g  NaN  NaN      6

In [53]:
pd.concat([df1,df2], axis=1, keys=['level1', 'level2'],
         names=['upper', 'lower'])

upper level1     level2     
lower  data1 key  data2  key
0          0   b      0    a
1          1   b      1    b
2          2   a      2    a
3          3   c      3    b
4          4   a      4    d
5          5   b    NaN  NaN

In [54]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
df1

a         b         c         d
0 -0.068913 -0.021615  0.201576 -0.517171
1  1.648350 -0.645454  1.612198  1.702438
2 -1.588012 -1.118213  1.701616  0.182061

In [55]:
df2

b         d         a
0 -0.970372  0.355651  0.539528
1 -0.195660 -0.519278 -2.130403

In [56]:
pd.concat([df1,df2], ignore_index=True)

a         b         c         d
0 -0.068913 -0.021615  0.201576 -0.517171
1  1.648350 -0.645454  1.612198  1.702438
2 -1.588012 -1.118213  1.701616  0.182061
3  0.539528 -0.970372       NaN  0.355651
4 -2.130403 -0.195660       NaN -0.519278

In [58]:
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
          index=['f', 'e', 'd', 'c', 'b', 'a'])
b = Series(np.arange(len(a), dtype=np.float64),
          index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [59]:
b

f     0
e     1
d     2
c     3
b     4
a   NaN
dtype: float64

In [60]:
np.where(pd.isnull(a), b, a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [61]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [62]:
df1 = DataFrame({'a': [1., np.nan, 5., np.nan],
                'b':[np.nan, 2., np.nan, 6.],
                'c': range(2, 18, 4)})
df2 = DataFrame({'a': [5., 4., np.nan, 3., 7.],
                'b': [np.nan, 3., 4., 6., 8.]})
df1.combine_first(df2)

a   b   c
0  1 NaN   2
1  4   2   6
2  5   4  10
3  3   6  14
4  7   8 NaN

In [63]:
data = DataFrame(np.arange(6).reshape((2, 3)),
                index=pd.Index(['Ohio', 'Colorado'], name='state'),
                columns=pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [73]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [66]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [67]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [68]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [69]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c' ,'d'])
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2.unstack()

a   b  c  d   e
one   0   1  2  3 NaN
two NaN NaN  4  5   6

In [70]:
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: float64

In [71]:
data2.unstack().stack(dropna=False)

one  a     0
     b     1
     c     2
     d     3
     e   NaN
two  a   NaN
     b   NaN
     c     4
     d     5
     e     6
dtype: float64

In [94]:
test = data.stack()
df = DataFrame({'left'：result, 'right': result + 5},
              columns = pd.Index(['left', 'right'], name='side'))
df

SyntaxError: invalid character in identifier (<ipython-input-94-18d00d37a25c>, line 2)

In [78]:
df.unstack('state')
df.unstack('state').stack('side')

NameError: name 'df' is not defined

In [95]:
ldata[:10]

NameError: name 'ldata' is not defined